// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plmmxaitwgbzglmbgckd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbW14YWl0d2diemdsbWJnY2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTAwNTUsImV4cCI6MjA2MzU2NjA1NX0.eFo1EbbBTPRjBsPmfaScKvF7ylcH6mnbvhLv-kNmGTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);